version: "3"
services:
    datascience-notebook:
        image: jupyter/datascience-notebook:python-3.8
        volumes:
            - ./:/home/jovyan
        ports:
            - 8888:8888
        container_name: datascience-notebook-container
